# Site settings
title: Advendtures in Software Development
email: joe.meirow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Software Development is my blog where I write about things I am learning or commentary I want to share from all aspects of the art and science of software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: motownjoe
github_username:  jmeirow


# Build settings
markdown: kramdown
